install.packages("weathermetrics", repos = 'http://cran.us.r-project.org')
install.packages("knitr", repos='http://cran.us.r-project.org')
install.packages("doBy", repos='http://cran.us.r-project.org')
install.packages("markdown", repos='http://cran.us.r-project.org')
install.packages("ggplot2", repos='http://cran.us.r-project.org')
install.packages("plyr", repos='http://cran.us.r-project.org')
install.packages("sqldf", repos='http://cran.us.r-project.org')
install.packages("lubridate", repos='http://cran.us.r-project.org')
install.packages("formatR", repos='http://cran.us.r-project.org')
install.packages("pander", repos='http://cran.us.r-project.org')

library(weathermetrics)
library(knitr)
library(doBy)
library(markdown)
library(ggplot2)
library(plyr)
library(sqldf)
library(lubridate)
library(formatR)
library(pander)

